# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.media import Media  # noqa: F401,E501
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class PostWithoutTimeAndId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: User=None, message: str=None, media: Media=None):  # noqa: E501
        """PostWithoutTimeAndId - a model defined in Swagger

        :param user: The user of this PostWithoutTimeAndId.  # noqa: E501
        :type user: User
        :param message: The message of this PostWithoutTimeAndId.  # noqa: E501
        :type message: str
        :param media: The media of this PostWithoutTimeAndId.  # noqa: E501
        :type media: Media
        """
        self.swagger_types = {
            'user': User,
            'message': str,
            'media': Media
        }

        self.attribute_map = {
            'user': 'user',
            'message': 'message',
            'media': 'media'
        }
        self._user = user
        self._message = message
        self._media = media

    @classmethod
    def from_dict(cls, dikt) -> 'PostWithoutTimeAndId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostWithoutTimeAndId of this PostWithoutTimeAndId.  # noqa: E501
        :rtype: PostWithoutTimeAndId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this PostWithoutTimeAndId.


        :return: The user of this PostWithoutTimeAndId.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this PostWithoutTimeAndId.


        :param user: The user of this PostWithoutTimeAndId.
        :type user: User
        """

        self._user = user

    @property
    def message(self) -> str:
        """Gets the message of this PostWithoutTimeAndId.


        :return: The message of this PostWithoutTimeAndId.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this PostWithoutTimeAndId.


        :param message: The message of this PostWithoutTimeAndId.
        :type message: str
        """

        self._message = message

    @property
    def media(self) -> Media:
        """Gets the media of this PostWithoutTimeAndId.


        :return: The media of this PostWithoutTimeAndId.
        :rtype: Media
        """
        return self._media

    @media.setter
    def media(self, media: Media):
        """Sets the media of this PostWithoutTimeAndId.


        :param media: The media of this PostWithoutTimeAndId.
        :type media: Media
        """

        self._media = media
