# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.media import Media  # noqa: F401,E501
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class Post(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, timestamp: date=None, user: User=None, message: str=None, media: Media=None):  # noqa: E501
        """Post - a model defined in Swagger

        :param id: The id of this Post.  # noqa: E501
        :type id: str
        :param timestamp: The timestamp of this Post.  # noqa: E501
        :type timestamp: date
        :param user: The user of this Post.  # noqa: E501
        :type user: User
        :param message: The message of this Post.  # noqa: E501
        :type message: str
        :param media: The media of this Post.  # noqa: E501
        :type media: Media
        """
        self.swagger_types = {
            'id': str,
            'timestamp': date,
            'user': User,
            'message': str,
            'media': Media
        }

        self.attribute_map = {
            'id': 'id',
            'timestamp': 'timestamp',
            'user': 'user',
            'message': 'message',
            'media': 'media'
        }
        self._id = id
        self._timestamp = timestamp
        self._user = user
        self._message = message
        self._media = media

    @classmethod
    def from_dict(cls, dikt) -> 'Post':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Post of this Post.  # noqa: E501
        :rtype: Post
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Post.


        :return: The id of this Post.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Post.


        :param id: The id of this Post.
        :type id: str
        """

        self._id = id

    @property
    def timestamp(self) -> date:
        """Gets the timestamp of this Post.


        :return: The timestamp of this Post.
        :rtype: date
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: date):
        """Sets the timestamp of this Post.


        :param timestamp: The timestamp of this Post.
        :type timestamp: date
        """

        self._timestamp = timestamp

    @property
    def user(self) -> User:
        """Gets the user of this Post.


        :return: The user of this Post.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this Post.


        :param user: The user of this Post.
        :type user: User
        """

        self._user = user

    @property
    def message(self) -> str:
        """Gets the message of this Post.


        :return: The message of this Post.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Post.


        :param message: The message of this Post.
        :type message: str
        """

        self._message = message

    @property
    def media(self) -> Media:
        """Gets the media of this Post.


        :return: The media of this Post.
        :rtype: Media
        """
        return self._media

    @media.setter
    def media(self, media: Media):
        """Sets the media of this Post.


        :param media: The media of this Post.
        :type media: Media
        """

        self._media = media
